---
parent: 'common/test_cases/origin_installed_release.yml'
overrides:
  timer: 'H H * * *'
  email:
    - bparees@redhat.com
    - cewong@redhat.com
    - gmontero@redhat.com
    - cdaley@redhat.com
    - jminter@redhat.com
extensions:
  actions:
    - type: "script"
      title: "run extended tests"
      repository: "origin"
      script: |-
        KUBECONFIG=/etc/origin/master/admin.kubeconfig TEST_ONLY=true JUNIT_REPORT='true' make test-extended SUITE=core FOCUS="\[builds\]"
